FROM node:latest AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci --legacy-peer-deps

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY ./nginx/app.conf /etc/nginx/app.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
