name: Build, Test, and Deploy with Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to DockerHub (or GitHub Container Registry)
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker Image
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/algorithm-calendar:latest -f Dockerfile.prod .

      # Step 5: Run Unit Tests (if tests are part of the container)
      #- name: Run tests in Docker container
      #  run: |
      #    docker run --rm ${{ secrets.DOCKER_USERNAME }}/algorithm-calendar:latest npm test  # Adjust to your test command

      # Step 6: Push Docker Image to Registry
      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/algorithm-calendar:latest

      # Step 7: Set up the SSH key for connecting to your server
      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/algorithm-calendar.pem
          chmod 600 ~/.ssh/algorithm-calendar.pem
          ssh-keyscan -H 3.108.235.202 >> ~/.ssh/known_hosts

      # Step 8: Optionally Deploy the Docker image to your server
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Set up SSH connection (replace with your actual deploy script)
          ssh -i -i ~/.ssh/algorithm-calendar.pem ec2-user@3.108.235.202 "docker pull ${{ secrets.DOCKER_USERNAME }}/algorithm-calendar:latest && docker run -d -p 80:80 --name=algorithm-calendar-app"
